version: '3.8'

services:
  postgis:
    image: postgis/postgis:17-3.5  # Official PostGIS image
    container_name: postgis
    restart: always
    environment:
      POSTGRES_DB: geodata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  geoserver:
    image: geoserver-with-vectortiles
    container_name: geoserver
    restart: always
    depends_on:
      - postgis
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*      
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=origin,content-type,accept,authorization
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

volumes:
  postgis_data:
  geoserver_data: